### ISSUE TITLE
Load/view simulation problem

### ISSUE THREAD

**Issue by rythorpe** [jonescompneurolab/hnn#77] opened 2019-08-20 17:27 UTC
I noticed a few issues with how the GUI now loads param files.

1) Upon loading a new param file, the theoretical evoked input time distributions do not update accordingly.

2) When running a new simulation (loading a param file without an associated output data file), the y-axis does not rescale correctly.

3) The simulation drop-down menu at the bottom does not show that the default param simulation is active. See the screenshot below.

![Screen Shot 2019-08-20 at 1 13 49 PM](https://user-images.githubusercontent.com/20212206/63369331-b51d3880-c34d-11e9-998c-8404485a3904.png)

**Comment by rythorpe** [comment] 2019-08-20 17:43
Also, the x-axis isn't limited by the length of the simulation, rather, it seems to include all of the loaded data timepoints.

**Comment by blakecaldwell** [comment] 2019-08-20 19:54
Thank you. I found the fixes to 2, 3. Couldn't reproduce 1, but please let me know if you see it happen.

**Comment by rythorpe** [comment] 2019-08-20 20:14
I can't reproduce 1 either, so just ignore it.

**Comment by blakecaldwell** [comment] 2019-09-04 17:05
@rythorpe Thanks for finding this. It is fixed now.

**Closed** 2019-09-04 17:05 UTC
Labels: bug
