### ISSUE TITLE
Installation problem with Xauth on Mac

### ISSUE THREAD

**Issue by kevin-spencer** [jonescompneurolab/hnn#188] opened 2020-03-16 15:30 UTC
Hi there -- I'm trying to install HNN on a Macbook Pro running Mojave. The latest version of XQuartz is installed and works with another app. (I reinstalled it and still get this problem.) The Docker error message is:

Checking if XQuartz is installed... done
Checking for xauth... done
Retrieving current X11 authentication keys... XQuartz authentication keys need to be updated
Restarting XQuartz... done
Error: still no keys valid keys
Please see hnn_docker.log for more details

I'm attaching hnn_docker.log. I read the other Xauth problem by a Windows user and verified that .Xauthority seems to be rewritten each time XQuartz is started during the install.

Thanks for your help-
Kevin
[hnn_docker.log](https://github.com/jonescompneurolab/hnn/files/4338921/hnn_docker.log)

**Comment by blakecaldwell** [comment] 2020-03-16 15:50
Hi @kevin-spencer. Thanks for letting us know. This could be related to Apple's X11 server that came with snow leopard, and in your case, a system xauth binary is getting called instead of the XQuartz version. It looks like the hnn_docker.sh script is using /usr/bin/xauth, where on my system it uses /opt/X11/bin/xauth. The quick fix would be to rename /usr/bin/xauth to somethine else and run the script again. Could you try that first?

If it works, I'll know what the check for in the script and will update HNN with a more complete fix.

**Comment by kevin-spencer** [comment] 2020-03-16 19:26
Hi Blake,

Unfortunately my expertise with MacOS is not so great that I can rename /usr/bin/xauth, as I don't have permission and can't seem to make my Mac give me permission. Do you have any suggestions?

Thanks,
Kevin
________________________________

**Comment by blakecaldwell** [comment] 2020-03-16 19:30
Hi Kevin,

Oh, sure, that makes sense from the command line. Let's try with finder. From the 'Go' menu select 'Go to Folder' and then type `/usr/bin`. You should be able to find `xauth` and rename it/move it to the recycle bin and the OS will ask you for a password to do so.

**Comment by kevin-spencer** [comment] 2020-03-16 21:50
I tried that and it wouldn't even let me delete it, saying "xauth can't be modified or deleted because it's required by macOS". I tried doing it directly from a terminal window too. Couldn't change the permissions on it either.

The shell won't allow me to login as superuser. There must be a way that I can give myself access but I'm not familiar with this side of the Mac. If you have any ideas they'd be appreciated!

Thanks,
Kevin
________________________________

**Comment by kevin-spencer** [comment] 2020-03-17 21:22
So I found out how to get root access, got it, and the OS still wouldn't let me do anything in /usr/bin, even though I appear to have write access... This is a tough one.
________________________________

**Comment by blakecaldwell** [comment] 2020-03-17 21:32
Thanks for checking that. I'm working on a fix to try that should fix it without needing to change that. Stay tuned.

**Comment by kevin-spencer** [comment] 2020-03-17 21:43
thanks!
________________________________

**Comment by blakecaldwell** [comment] 2020-03-17 22:23
Could you try the new code by running the following commands from the `hnn` directory:
```
git fetch origin pull/189/head:issue_188
git checkout issue_188
./hnn_docker.sh start
```

If that works, I'll push the code to the repository. Afterward, you can switch back to the lastest code by.
```
git checkout master
git pull origin master
```

**Comment by kevin-spencer** [comment] 2020-03-17 22:28
The first command didn't work. The error message was:

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

________________________________

**Comment by blakecaldwell** [comment] 2020-03-17 22:31
Oops. Looks like one more command to install the Xcode command-line tools (including `git`)
```
xcode-select --install
```

**Comment by kevin-spencer** [comment] 2020-03-17 23:07
OK, Xcode is installed, but when I run your first git command:

fatal: not a git repository (or any of the parent directories): .git
________________________________

**Comment by blakecaldwell** [comment] 2020-03-17 23:12
Oh sorry, I made a faulty assumption that you used git to download the hnn code. Try cloning to a new directory.
```
git clone https://github.com/jonescompneurolab/hnn.git hnn-git
cd hnn-git
```

This will be a duplicate of the directory that you already have, but the `git fetch` command should work.

**Comment by kevin-spencer** [comment] 2020-03-20 04:39
That worked! Thanks very much for your help, Blake.

Kevin
________________________________

**Comment by blakecaldwell** [comment] 2020-03-20 10:51
Fantastic! Thanks, Kevin.

**Closed** 2020-03-20 10:51 UTC
